dist: focal
language: minimal
env:
  - ARCH="linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64" IMAGE_NAME="tor-proxy"

services:
  - docker

addons:
  apt:
    packages:
      - qemu
      - binfmt-support
      - qemu-user-static
      - jq

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

stages:
  - name: test
  - name: dev
    if: branch = master
  - name: prod
    if: tag IS present
  - name: dockerhub_readme



jobs:
  include:
  - stage: test
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ${DOCKER_USERNAME}/${IMAGE_NAME}:test_${TRAVIS_COMMIT} .
    - docker push ${DOCKER_USERNAME}/${IMAGE_NAME}:test_${TRAVIS_COMMIT}
    - docker run -d --restart=always --name tor-proxy -p 9150:9150 ${DOCKER_USERNAME}/${IMAGE_NAME}:test_${TRAVIS_COMMIT}
    - sleep 60
    - curl --fail --socks5-hostname localhost:9150 -I -L 'https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/' || exit 1
    - |
      HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "$DOCKER_USERNAME", "password": "$DOCKER_PASSWORD"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
      curl -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${IMAGE_NAME}/tags/test_${TRAVIS_COMMIT}/


  - stage: dev
    script:
    - docker buildx create --name mybuilder --platform $ARCH
    - docker buildx use mybuilder
    - docker buildx inspect
    - docker buildx inspect --bootstrap
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build --platform $ARCH -t ${DOCKER_USERNAME}/${IMAGE_NAME}:dev . --push

  - stage: prod
    script:
    - docker buildx create --name mybuilder --platform $ARCH
    - docker buildx use mybuilder
    - docker buildx inspect
    - docker buildx inspect --bootstrap
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build --platform $ARCH -t ${DOCKER_USERNAME}/${IMAGE_NAME}:${TRAVIS_TAG} -t ${DOCKER_USERNAME}/${IMAGE_NAME}:latest . --push

  - stage: dockerhub_readme
    script:
    - docker run -v $PWD:/workspace -e DOCKERHUB_USERNAME=$DOCKER_USERNAME -e DOCKERHUB_PASSWORD=$DOCKER_PASSWORD -e DOCKERHUB_REPOSITORY=${DOCKER_USERNAME}/${IMAGE_NAME} -e README_FILEPATH=/workspace/README.md peterevans/dockerhub-description:2
  

  
