dist: focal
language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - qemu
      - binfmt-support
      - qemu-user-static

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

stages:
  - name: dev
    if: branch = master
  - name: prod
    if: tag IS present  


jobs:
  include:
  - stage: dev
    script:
    - docker buildx create --name mybuilder --platform linux/arm,linux/arm64,linux/amd64
    - docker buildx use mybuilder
    - docker buildx inspect
    - docker buildx inspect --bootstrap
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64 -t piwi3910/tor-proxy:dev . --push

  - stage: prod
    script:
    - docker buildx create --name mybuilder --platform linux/arm,linux/arm64,linux/amd64
    - docker buildx use mybuilder
    - docker buildx inspect
    - docker buildx inspect --bootstrap
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64 -t piwi3910/tor-proxy:$TRAVIS_TAG -t piwi3910/tor-proxy:latest . --push

  
